### ISSUE TITLE
Roadmap a11y

### ISSUE THREAD

**Issue by donni106** [smart-village-solutions/smart-village-app-app#114]
# Roadmap a11y

There is a huge update with version 1.3.2 on accessibility. We made a big step but are also far away from a perfect situation.
Following features can be discussed and implemented in the future:

- [ ] count items in list and add the index to accessibility labels
- [ ] Accommodate zoom levels and different text sizes
- [ ] Error states/messages for slow computing power or slow internet

**Comment by SoleCincis** [comment]
[Robo test](https://medium.com/wantedly-engineering/android-application-testing-with-firebase-robo-test-c674e1754298) is meant to be a layer on top of our existing unit and instrumentation tests. It is a very good tool to simulate user interactions and to automatically validate our app against different multiple devices at once. So it's meant to be used to find performance and user experience issues, not to test for correctness.

[Accessibility Test results ](https://console.firebase.google.com/u/1/project/sva-bad-belzig/testlab/histories/bh.aa4c057fd21481cb/matrices/5082143307455685380/executions/bs.864071291382eb57/a11y#contentLabeling) are not flawless but still very useful. Here an example of a correct test and a wrong test : 

**It's correct splash screen dosen't have a label.** 
<img width="600" alt="Screenshot 2020-11-02 at 12 41 32" src="https://user-images.githubusercontent.com/43641321/97866371-1b506a00-1d0c-11eb-9472-549b91d4e474.png"> 

**It's wrong there is no text item here** 
<img width="600" alt="Screenshot 2020-11-02 at 12 42 15" src="https://user-images.githubusercontent.com/43641321/97866496-53f04380-1d0c-11eb-8cf4-af65fe441032.png"> 


As I don't have any Android device available to test the app. Robo test seems like a good alternative solution to me. 
Although I am confused on how to run Robo test on my own.

**Comment by SoleCincis** [comment]
**Touch targets should be at least 44 px (10 mm):** 
this warning from robo test shows that  our button touch area should be wider. 
![](https://user-images.githubusercontent.com/43641321/121702930-949a1180-cad2-11eb-8576-fd60eeebe085.png)

**Low contrast**
this warning shows that our drawer header should be a color that is in contrast with the drawer. What color should be?
![](https://user-images.githubusercontent.com/43641321/121703509-36216300-cad3-11eb-9179-18f4979537d3.png)

**Comment by donni106** [comment]
closing this, as we are on several improvements according a11y this year
